replace WP_ENV with WP_ENVIRONMENT_TYPE - WP v5.5
code-soup/pumpkin pull request #19
Opened 2020-08-31 12:57 UTC by piqusy

issue #18

2020-09-07 08:57 UTC, Bobz-zg commented
1. Stavi po defaultu da bude 'production'
2. Koristi define `WP_ENVIRONMENT_TYPE` dalje za provjeru `if WP_ENVIRONMENT_TYPE !== dev..`

2020-09-07 09:01 UTC, Bobz-zg requested changes
Gore sam stavio u komentar

2020-09-09 04:14 UTC, Bobz-zg requested changes
Iz nekog razloga imamo dva puta isti kod za `add_filter('acf/settings/show_admin', '__return_false');` makni ovaj iz functions.php

2020-09-09 08:23 UTC, piqusy commented
Nije to jedni duplić, čini se da je ovaj [folder](https://github.com/code-soup/pumpkin/tree/master/inc/setup/acf) viška.
To je speglano u namespacing branchu, iako tamo je taj folder onaj koji sadrži bitan kod. A ovih par "../acf-" fajlova i acf-json u root folderu su zbrisani.

2020-09-09 08:50 UTC, Bobz-zg commented
Hm, ok. Morat ću namespacing onda rješit da možemo dalje.

2020-09-09 08:50 UTC, merged